# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29a757c821f2bbc5ee35aa9619a155d658c50d4a4369547375cb5a1ff422e3a244f4e5cc6cde485a987b847c8b6b4b577ce3e7918552d6b4093d10798f1d0b9d

test:
  secret_key_base: d18dc2ef3fb66a38f7c9423d79b0812f9fc062f8f44c370087990e7f4f4724881b4cf4624ba95f54ba59b127a814105c9b98f3bc804ad5599faceaa9b78a0345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
